// templates/svelte/default/demo/react-demo/src/App.js
import React from 'react'
import SveltePlugin from './<%-NAME>-react.js'
import Styles from './<%-NAME>.css'
function App() {
  const handleClick = () => alert('alert from react')
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <SveltePlugin
          onSvelteclick={handleClick}
          name="(attr passed from react js to svlete)"
        />
      </header>
    </div>
  )
}

export default App

// templates/svelte/default/demo/vue/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./logo.png">
    <SveltePlugin 
    @onSampleEvent="handleClick" 
    @onSampleEventOver="handleOver" 
    :options="{
       sampleConfig: 'passed from vue js'
    }" />
  </div>
</template>
<script>
import SveltePlugin from '../../../public/[NAME]-vue.js'
import styles from '../../../public/awesome-unip.css'
export default {
  name: 'app',
  components: { SveltePlugin},
  methods: {
    handleOver () {
      console.log('Vue handle mouse over vue js')
    },
    handleClick () {
      alert('alert from vue js')
    }
  }
}
</script>

<style>
#app {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
